// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.21.0

package db

import (
	"time"
)

type Account struct {
	ID        int32     `json:"id"`
	Username  string    `json:"username"`
	Email     string    `json:"email"`
	Password  string    `json:"password"`
	CreatedAt time.Time `json:"created_at"`
}

type Notary struct {
	NotaryID   int32  `json:"notary_id"`
	NotaryName string `json:"notary_name"`
}

type Order struct {
	OrderID       int64     `json:"order_id"`
	IssuedDate    time.Time `json:"issued_date"`
	Name          string    `json:"name"`
	Surname       string    `json:"surname"`
	PhoneNumber   string    `json:"phone_number"`
	LanguageFrom  string    `json:"language_from"`
	LanguageTo    string    `json:"language_to"`
	NumberOfPages int32     `json:"number_of_pages"`
	NotaryID      int32     `json:"notary_id"`
	TotalPayment  string    `json:"total_payment"`
	DownPayment   string    `json:"down_payment"`
	Remaining     string    `json:"remaining"`
	TranslatorID  int32     `json:"translator_id"`
	Expenses      string    `json:"expenses"`
	StatusID      int32     `json:"status_id"`
	Details       string    `json:"details"`
}

type Status struct {
	StatusID   int32  `json:"status_id"`
	StatusName string `json:"status_name"`
}

type Token struct {
	ID        int32     `json:"id"`
	Token     string    `json:"token"`
	AccountID int32     `json:"account_id"`
	CreatedAt time.Time `json:"created_at"`
	ExpiresAt time.Time `json:"expires_at"`
}

type Translator struct {
	TranslatorID int64  `json:"translator_id"`
	Name         string `json:"name"`
	Surname      string `json:"surname"`
	PhoneNumber  string `json:"phone_number"`
	Email        string `json:"email"`
}
